apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
  namespace: bootstrap
subjects:
- kind: ServiceAccount
  name: default
  namespace: bootstrap
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
