apiVersion: v1
kind: Service
metadata:
  namespace: bootstrap
  name: peer-service
spec:
  selector:
    app: peer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP